-- MySQL Script generated by MySQL Workbench
-- 12/17/16 10:15:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema takonseek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema takonseek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `takonseek` DEFAULT CHARACTER SET utf8 ;
USE `takonseek` ;

-- -----------------------------------------------------
-- Table `takonseek`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takonseek`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takonseek`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takonseek`.`video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(45) NULL,
  `nama_video` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takonseek`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takonseek`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` VARCHAR(400) NULL,
  `date_posted` TIMESTAMP NULL,
  `user_id` INT NOT NULL,
  `video_id` INT NULL,
  `category` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_user1_idx` (`user_id` ASC),
  INDEX `fk_question_video1_idx` (`video_id` ASC),
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `takonseek`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `takonseek`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `takonseek`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `takonseek`.`answer` (
  `id` INT NOT NULL,
  `text` VARCHAR(500) NULL,
  `status` CHAR(1) NULL,
  `date_posted` TIMESTAMP NULL,
  `user_id` INT NOT NULL,
  `video_id` INT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_user1_idx` (`user_id` ASC),
  INDEX `fk_answer_video1_idx` (`video_id` ASC),
  INDEX `fk_answer_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `takonseek`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `takonseek`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `takonseek`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
